// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkrYLCFYW145TRcbp0Eye1vT4aKE5DNW4',
    appId: '1:349516420887:web:0810bca94c0ed3dddf8952',
    messagingSenderId: '349516420887',
    projectId: 'zaboteru',
    authDomain: 'zaboteru.firebaseapp.com',
    databaseURL: 'https://zaboteru-default-rtdb.firebaseio.com',
    storageBucket: 'zaboteru.appspot.com',
    measurementId: 'G-NM443T6SLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATsvEh7cJHAN359_mIT06Xj4Rslhu8YAA',
    appId: '1:349516420887:android:dca655bb08eafa56df8952',
    messagingSenderId: '349516420887',
    projectId: 'zaboteru',
    databaseURL: 'https://zaboteru-default-rtdb.firebaseio.com',
    storageBucket: 'zaboteru.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC12H5AURGAyEIvz1l7GswnThMtDaRzhNA',
    appId: '1:349516420887:ios:e3a33fc4b1e819d3df8952',
    messagingSenderId: '349516420887',
    projectId: 'zaboteru',
    databaseURL: 'https://zaboteru-default-rtdb.firebaseio.com',
    storageBucket: 'zaboteru.appspot.com',
    iosBundleId: 'com.example.zaboteru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC12H5AURGAyEIvz1l7GswnThMtDaRzhNA',
    appId: '1:349516420887:ios:8542daccdb554929df8952',
    messagingSenderId: '349516420887',
    projectId: 'zaboteru',
    databaseURL: 'https://zaboteru-default-rtdb.firebaseio.com',
    storageBucket: 'zaboteru.appspot.com',
    iosBundleId: 'com.example.zaboteru.RunnerTests',
  );
}
