name: zaboteru
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.1
  provider: ^6.1.1
  line_icons: ^2.0.3
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  firebase_core: ^3.10.1
  device_preview: ^1.1.0
  percent_indicator: ^4.2.3
  firebase_database: ^11.3.1
  flutter_screenutil: ^5.9.0
  awesome_notifications: ^0.10.0
  animated_splash_screen: ^1.3.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - assets/google_fonts/

fonts:
  - family: Nunito
    fonts:
      - asset: assets/google_fonts/Nunito-Regular.ttf

  - family: Nunito-Italic
    fonts:
      - asset: assets/google_fonts/Nunito-Italic.ttf
        weight: 400

  - family: Nunito-Bold
    fonts:
      - asset: assets/google_fonts/Nunito-Bold.ttf
        weight: 700
        
  - family: Nunito-ExtraBold
    fonts:
      - asset: assets/google_fonts/Nunito-ExtraBold.ttf
        weight: 800

  - family: Nunito-Light
    fonts:
      - asset: assets/google_fonts/Nunito-Light.ttf
        weight: 300

      # - asset: fonts/Nunito/Nunito-SemiBoldItalic.ttf
      # - asset: fonts/Nunito/Nunito-VariableFont.ttf
      # - asset: fonts/Nunito/Nunito-LightItalic.ttf
      # - asset: fonts/Nunito/Nunito-Medium.ttf
      # - asset: fonts/Nunito/Nunito-MediumItalic.ttf
      # - asset: fonts/Nunito/Nunito-BoldItalic.ttf
      # - asset: fonts/Nunito/Nunito-ExtraBold.ttf
      # - asset: fonts/Nunito/Nunito-Italic-VariableFont_wght.ttf